### ISSUE TITLE
流量观看提示怎么关闭啊？

### ISSUE THREAD

**Issue by MeiJiuDD** [670848654/SakuraAnime#13]
流量观看的时候一直停在屏幕中间，也没办法关闭，一点击视频就暂停不播了，再点击开始播放视频也不播放就一直跳提示。设置里也找不到关闭的地方。

**Comment by 670848654** [comment]
那个弹窗右下角是有按钮的，主题冲突，按钮文字颜色和背景色一样，所以看不见了。

MeiJiuDD ***@***.***> 于 2021年4月17日周六 21:17写道：
