### ISSUE TITLE
关于弹幕

### ISSUE THREAD

**Issue by 1759350586** [670848654/SakuraAnime#21]
出一个有弹幕的功能

**Comment by 670848654** [comment]
这只是个爬虫应用，数据都来源于网站 无法添加这种功能🌚。

1759350586 ***@***.***> 于 2021年7月2日周五 12:34写道：

**Comment by ZhuChengrui2004** [comment]
可惜这网站用户少，弹幕也少

**Comment by KH-XXXVillager** [comment]
> 可惜这网站用户少，弹幕也少

其实也不少，但樱花官网常挂，高仿多，不好统一
