### ISSUE TITLE
安卓十一闪退

### ISSUE THREAD

**Issue by iapbay** [670848654/SakuraAnime#27]
安卓十一给完内存权限就闪退重启后怎么点都打不开

**Comment by 670848654** [comment]
这个权限给了没有
![Screenshot_20220101-095739.jpg](https://user-images.githubusercontent.com/18481749/147842519-d111b3f5-1807-4330-91e1-b9899bfebab1.jpg)

**Comment by iapbay** [comment]
![Screenshot_2022-01-01-10-15-00-340_com android settings](https://user-images.githubusercontent.com/95968813/147842704-5d4f689e-ca8e-4ac6-9da6-ce7c6ca2fcc0.jpg)
给了我连root权限都给他隐藏了

**Comment by 670848654** [comment]
😅MIUI吗，我手里的小米安卓11也是正常的，不过没有root，难道和magisk模块有冲突？比如安装了重定向之类的模块…

**Comment by iapbay** [comment]
我之前用的时候有重定向的模块也可以用现在关了也用不了了

**Comment by iapbay** [comment]
我模块全关了也是用不了

**Comment by 670848654** [comment]
文件目录里有这个文件夹没呢
![Screenshot_20220101-104619.jpg](https://user-images.githubusercontent.com/18481749/147842963-c3d620ee-34a3-4114-b00d-b2ce33844396.jpg)

**Comment by iapbay** [comment]
没

**Comment by 670848654** [comment]
应用给到权限后会初始化该目录，没有就很奇怪了。

**Comment by 670848654** [comment]
试试在存储目录中解压这个压缩文件。
[SakuraAnime.zip](https://github.com/670848654/SakuraAnime/files/7797324/SakuraAnime.zip)

**Comment by iapbay** [comment]
没有用根目录也是

**Comment by 670848654** [comment]
我手上的也是安卓11的miui，运行没有问题。![Screenshot_2022-01-01-11-20-21-857_my.project.sakuraproject.jpg](https://user-images.githubusercontent.com/18481749/147843308-6da2581c-dba0-48af-a351-deafcf38cde9.jpg)![Screenshot_2022-01-01-11-18-59-806_com.android.settings.jpg](https://user-images.githubusercontent.com/18481749/147843310-beb9840b-70fb-4da3-9138-41ea5cb82e1a.jpg)

**Comment by iapbay** [comment]
回头我刷机试试吧

**Comment by 670848654** [comment]
我没root，所以我怀疑可能是Magisk/Xposed模块的问题😂
