### ISSUE TITLE
播放源问题

### ISSUE THREAD

**Issue by 1983shake** [670848654/SakuraAnime#30]
作者你好。现在app里动漫播放源已经很多都在失效了，能否重新更换播放源？谢谢。

**Comment by 670848654** [comment]
首页点击标题栏可以切换到imomoe源，试试imomoe的资源。

**Comment by 1983shake** [comment]
哦哦，现在才知道标题栏可以切换T_T。
好的，可惜历史记录和播放记录得重新弄了。
谢谢了。

**Comment by ZakiuC** [comment]
作者你好，imomoe源加载不了了，可以修复一下吗

**Comment by 670848654** [comment]
检查你的网络能不能正常访问该网站。

ZakiuC ***@***.***> 于 2022年3月9日周三 07:24写道：
