### ISSUE TITLE
小bug和小建议

### ISSUE THREAD

**Issue by PYUDNG** [670848654/SakuraAnime#35]
一个小bug：在下载时进度条左侧上方“下载中”三个字下面始终显示`0B`，如图
![image](https://user-images.githubusercontent.com/63054558/173200436-9ec4671d-7661-47f9-9523-69f59f45e2b9.png)

**Comment by PYUDNG** [comment]
一个小建议：如图，下载列表界面，正在下载的动漫会显示当前正在下载的那一集的进度，而不是该动漫全部集的整体进度
感觉显示整体进度会稍微更好一点，如果无法在其他未下载集开始下载前获取到文件大小的话，简单地显示一个`已下载集数/总集数`的文本在进度条上方也是好的，不知可否考虑
![image](https://user-images.githubusercontent.com/63054558/173200710-eed0a701-1ba3-43ae-be5d-59e057a3c5d3.png)

**Comment by 670848654** [comment]
1、下载显示0B这不是bug，因为下载的格式是m3u8，在下载时是不知道文件总大小的。
2、原先是也想设计成这种方案，但因测试后发现有问题才改为现在这种方式😁。
