### ISSUE TITLE
可以加弹幕功能吗？

### ISSUE THREAD

**Issue by daysplume** [670848654/SakuraAnime#38]
之前skyd666的客户端有弹幕，用的是这个弹幕引擎：https://github.com/MaybeQHL/my_danmu_pub 。不知道大佬能不能添加这个功能

**Comment by daysplume** [comment]
效果还是挺不错的
![微信图片_20220724222447](https://user-images.githubusercontent.com/29432706/180651677-6c229cf7-be06-492f-ba3c-0a1ba38987d2.jpg)

**Comment by Taotech114627** [comment]
大佬，你的数据源仓库打不开了
