### ISSUE TITLE
可以给追番列表和软件设置做一个备份的导入导出吗

### ISSUE THREAD

**Issue by 1164844282** [670848654/SakuraAnime#41]
因为有些时候刷机后app的追番列表无法备份

**Comment by 670848654** [comment]
> 因为有些时候刷机后app的追番列表无法备份

列表的话备份数据库文件，后期替换就行，软件设置暂不支持。
![Screenshot_2022-08-21-11-22-58-37_55bef12f624c2b805189a6aa783c400d.jpg](https://user-images.githubusercontent.com/18481749/185774276-6de888e0-f647-45c8-a5d6-653c8d5de100.jpg)

**Comment by 1164844282** [comment]
OK
