### ISSUE TITLE
类原生，安卓13,打开2.5.0直接闪退

### ISSUE THREAD

**Issue by 2832167832** [670848654/SakuraAnime#65]
20-20230610-NIGHTLY-lemonades

**Comment by 670848654** [comment]
在原生系统上是bug，权限问题，晚点更新个版本修复。
![1687665503961](https://github.com/670848654/SakuraAnime/assets/18481749/891e3d8f-d535-4866-8203-fd4afce032d6)

**Comment by 2832167832** [comment]
我在用Cleaner这个软件，它会导致安装的软件的appous文件权限为忽略，部分人用Cleaner就没这个问题，我昨天给了文件权限就不闪退了

**Comment by 670848654** [comment]
> 我在用Cleaner这个软件，它会导致安装的软件的appous文件权限为忽略，部分人用Cleaner就没这个问题，我昨天给了文件权限就不闪退了

😂安卓13权限变了，旧版本授权了覆盖安装新版本没问题，卸载重装就会闪退，但小米的设备有点奇怪，卸载重装不会出现。
