### ISSUE TITLE
下载相关的一些问题

### ISSUE THREAD

**Issue by NuoL5623** [670848654/SakuraAnime#69]
下载失败后删除了所有的下载任务，然后每次打开下载界面都会弹出还有N个下载任务还未完成的弹窗
没有显示任何下载任务，但是无论是清后台，删除内存中的文件等等操作后进入下载界面还是会弹出这个弹窗
不知道是下载的临时文件没有彻底删除掉还是后台的下载记录没有同步的删除掉哦
麻烦作者有空的时候可以测试一下，非常感谢！！

**Comment by 670848654** [comment]
暂时清除应用数据吧，有时间再调咯
