### ISSUE TITLE
赞！可否增加画质选项？

### ISSUE THREAD

**Issue by Vincerovo** [670848654/SakuraAnime#9]
这款APP十分简洁好用，感谢作者！
顺便想问下画质相关的问题，请问画质可以调节吗？
谢谢！

**Comment by 670848654** [comment]
不能，原网站上也没有画质选项😁

Vincerovo <notifications@github.com> 于 2021年3月6日周六 14:16写道：

**Comment by Vincerovo** [comment]
谢谢~
